version: '3.8'

services:
  api:
    image: ${DOCKER_IMAGE_NAME:-be-remote-device:latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be-remote-device
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      - APP_NAME=be-remote-device
      - APP_ENV=production
      - APP_PORT=8080
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - JWT_SECRET=${JWT_SECRET:-supersecretkey_change_in_production}
      - MASTER_API_KEY=${MASTER_API_KEY:-my-super-secret-master-key-12345}
      - DB_DRIVER=postgres
      - DB_HOST=${DB_HOST:-postgres} # Nama container database PostgreSQL di shared_network
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-remote_device_db}
      - DB_SSLMODE=${DB_SSLMODE:-disable}
    networks:
      - shared_network

networks:
  shared_network:
    external: true
